package auth

import (
	"crypto/sha256"
	"crypto/subtle"
	"strings"
	"time"

	"github.com/sadeq-n-yazdi/sshpilot-vallete/internal/domain"
	"github.com/sadeq-n-yazdi/sshpilot-vallete/internal/secrets"
)

// Pairing timings.
const (
	// PairingLifetime bounds how long a pairing may be approved and redeemed.
	//
	// Ten minutes is not a round number picked for tidiness: it is the security
	// parameter that makes a short user code safe. A user code is guessable in
	// principle, so what protects it is the product of its entropy, the rate at
	// which guesses can be made, and the window in which a guess is worth
	// anything. This constant is that window, and shortening it is the cheapest
	// of the three to tighten. Pairing is an interactive act -- someone is
	// looking at a screen -- so ten minutes is generous for the user and mean
	// for an attacker.
	PairingLifetime = 10 * time.Minute

	// PairingPollInterval is the minimum gap between two polls of the same
	// pairing, reported to the client and enforced by the server.
	//
	// It is enforced rather than merely advertised because a polling client is
	// the one participant guaranteed to be automated: a client with a retry loop
	// and no backoff turns enrollment into a self-inflicted denial of service on
	// the pairing store.
	PairingPollInterval = 5 * time.Second
)

// Sizes of the random material in a pairing.
const (
	// pairingSecretBytes is the length of the device code's secret half: 256
	// bits from crypto/rand.
	//
	// The device code and the user code have deliberately different entropy
	// budgets, because they are transported differently and only one of them is
	// typed by a human.
	//
	// The device code is generated by, and stays inside, the pairing client. No
	// person ever reads or retypes it, so it costs nothing to make it as large
	// as any other secret in this package. At 256 bits, guessing it is not a
	// threat model anyone has to reason about, which is what lets the redemption
	// path run without a rate limit: an unauthenticated caller cannot make
	// progress against it however many attempts it is allowed.
	//
	// The user code cannot be sized this way. See userCodeLen.
	pairingSecretBytes = 32

	// userCodeLen is the number of symbols in a user code. Eight symbols over
	// the 32-character alphabet below is exactly 40 bits.
	//
	// Forty bits is small, and it is small on purpose: a person reads this code
	// off one screen and types it into another, and a code long enough to be
	// unguessable on its own would not be transcribed correctly. So the user
	// code is NOT defended by its entropy alone. It is defended by the
	// conjunction of four things, and removing any one of them breaks it:
	//
	//  1. The ten-minute PairingLifetime above bounds the window.
	//  2. Approval is single-use: a pairing leaves the pending state once.
	//  3. The approval lookup is rate limited, so the number of guesses that
	//     fit inside the window is capped far below 2^40. See the enrollment
	//     service, which is the only caller of GetByUserCodeHash.
	//  4. Approval requires an already-authenticated owner session, so an
	//     anonymous party cannot mount the guessing attack at all.
	//
	// RFC 8628 section 5.2 reaches the same conclusion from the other end: it
	// permits a short user code precisely on the condition that the endpoint
	// consuming it is rate limited.
	userCodeLen = 8

	// userCodeGroup is how many symbols appear between the hyphens a rendered
	// user code is grouped with. Grouping is a transcription aid only; the
	// hyphens carry no information and are stripped on input.
	userCodeGroup = 4
)

// userCodeAlphabet is the symbol set a user code is drawn from: the digits 2-9
// and the letters A-Z with I and O removed.
//
// # Why these exclusions
//
// The code is read by a person and retyped, so the alphabet must not contain
// two symbols that render alike in the fonts a terminal or a browser will
// choose. The rule applied is that a confusion class is a defect only when it
// has MORE THAN ONE member in the alphabet: a glyph the reader might resolve two
// ways is a transcription failure, while a glyph with exactly one possible
// reading is not.
//
// Starting the digits at 2 removes '0' and '1'. Removing 'I' and 'O' then
// leaves each of the two classic classes with at most one member:
//
//   - the bar class {'1', 'I', 'L'} keeps only 'L';
//   - the round class {'0', 'O'} keeps none, since nothing else in the alphabet
//     renders as a bare circle.
//
// That leaves 8 + 24 = 32 symbols, and the power of two is worth having rather
// than a coincidence to note. Selecting a symbol by masking five bits off a
// random byte is uniform by construction. Selecting one with a modulo over a
// non-power-of-two alphabet is not: the low-numbered symbols come up more often,
// which shrinks the effective entropy of a code that has little to spare.
const userCodeAlphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"

// userCodeMask selects the low five bits of a random byte, which index
// userCodeAlphabet exactly.
const userCodeMask = 0x1f

// Device code wire format. The prefix is not a security control; it exists so a
// leaked string is recognizable to a secret scanner and so a refresh token
// presented where a device code belongs is refused on shape.
const deviceCodePrefix = "svd_"

// domain separation tags for the two digests below. They are inside the hashed
// input, so a digest computed for one purpose can never equal a digest computed
// for another, whatever the inputs.
//
// This matters here more than it usually does. The two digests live in adjacent
// columns of one row and are compared by different code paths with different
// protections: the device code path has none because it does not need any, and
// the user code path has a rate limit because it does. Without the tags, a
// value that hashed to a device code digest would also be accepted as a user
// code, and the weaker path's rate limit would be sitting in front of the
// stronger path's secret.
const (
	pairingDeviceTag = "vallet.auth.pairing.device.v1\x00"
	pairingUserTag   = "vallet.auth.pairing.user.v1\x00"
)

// newPairingID returns a fresh random pairing identifier. It uses the same 128
// bits as a refresh credential id, and for the same reason: it is a lookup key
// rather than a secret, but it is random so that holding one does not reveal
// how many exist or let a caller walk to its neighbors.
func newPairingID() domain.PairingID {
	return domain.PairingID(tokenEncoding.EncodeToString(randomBytes(credentialIDBytes)))
}

// newDeviceSecret returns the secret half of a device code.
//
// It calls randomBytes, which wraps crypto/rand.Read directly and has no error
// branch: since Go 1.24 that function either fills the buffer or terminates the
// program, so an error path here could only ever tempt a caller into carrying on
// with a short secret. math/rand is never acceptable for any value in this file.
func newDeviceSecret() []byte { return randomBytes(pairingSecretBytes) }

// hashDeviceSecret returns the digest stored in
// domain.DevicePairing.DeviceCodeHash. The secret itself is never persisted.
//
// It is a plain SHA-256 over a domain separation tag and the secret, chosen for
// the same reason hashRefreshSecret is: the input is 256 bits from crypto/rand,
// so it occupies no searchable space for a slow KDF to protect, and a KDF on an
// unauthenticated path is a denial-of-service amplifier an attacker triggers for
// free. There is no salt because there is no shared search space to precompute
// against when every secret is independently random.
func hashDeviceSecret(secret []byte) []byte {
	sum := sha256.Sum256(append([]byte(pairingDeviceTag), secret...))
	return sum[:]
}

// deviceSecretMatches reports whether secret hashes to stored, in constant time.
//
// The comparison is crypto/subtle's. bytes.Equal and == both compile to a
// byte-by-byte compare that returns as soon as it finds a difference, and that
// timing difference is an oracle an attacker uses to recover the stored digest
// one byte at a time. Digests are compared rather than raw secrets, so the
// length of the presented value leaks nothing either; ConstantTimeCompare
// returns 0 for unequal lengths, which also covers a truncated stored hash.
func deviceSecretMatches(stored, secret []byte) bool {
	return subtle.ConstantTimeCompare(stored, hashDeviceSecret(secret)) == 1
}

// hashUserCode returns the digest stored in domain.DevicePairing.UserCodeHash.
// code must already be normalized.
//
// # This digest is not what protects the user code
//
// SHA-256 over 40 bits is not a meaningful barrier: anyone holding a database
// dump recovers the code by exhaustion in negligible time. That is stated
// plainly rather than papered over, because the honest conclusion is that the
// user code's defenses are the ones listed at userCodeLen -- a ten-minute
// lifetime, single-use approval, a rate limit, and an authenticated approver --
// and the digest's job is only to keep a casual reader of the store from seeing
// live codes.
//
// A slow KDF would not change that conclusion and would cost two things it
// cannot afford. The column is a lookup key, so the digest must be
// deterministic and unsalted for GetByUserCodeHash to find a row at all, which
// removes the property a KDF is normally bought for. And a deliberately slow
// hash on the approval path hands a caller a way to burn server time per
// attempt, which is precisely the resource the rate limit exists to protect.
func hashUserCode(code string) []byte {
	sum := sha256.Sum256(append([]byte(pairingUserTag), code...))
	return sum[:]
}

// newUserCode returns a fresh user code in both the forms that are needed: the
// grouped rendering shown to a person, and the canonical rendering that
// hashUserCode is defined over.
//
// Both are returned rather than the caller normalizing the display form,
// because that call could only fail in a way no caller could handle -- a
// generated code that does not normalize is a bug in this function, not a
// runtime condition -- and an error branch that cannot be reached is a branch
// nobody can be sure is correct. Deriving the canonical form here makes the
// impossible case unrepresentable instead.
//
// Each symbol is drawn by masking five bits off a random byte, which indexes the
// 32-symbol alphabet uniformly. There is no rejection loop and no modulo,
// because there is nothing to reject: every five-bit value is a valid index.
func newUserCode() (display secrets.Redacted, canonical string) {
	raw := randomBytes(userCodeLen)
	var shown, plain strings.Builder
	for i, r := range raw {
		if i > 0 && i%userCodeGroup == 0 {
			shown.WriteByte('-')
		}
		sym := userCodeAlphabet[r&userCodeMask]
		shown.WriteByte(sym)
		plain.WriteByte(sym)
	}
	return secrets.NewRedacted(shown.String()), plain.String()
}

// normalizeUserCode converts a code as typed into the canonical form that
// hashUserCode is defined over.
//
// It uppercases, drops the grouping characters a user may or may not have
// copied, and folds the excluded members of a confusion class onto the one
// member the alphabet kept. Everything else is rejected.
//
// Only the bar class can be folded. Someone reading an 'L' may reasonably type
// '1' or 'I', and since neither is ever produced by newUserCode, both map onto
// exactly one alphabet symbol -- so no two distinct valid codes can normalize to
// the same value, and the fold costs no entropy.
//
// '0' and 'O' are NOT folded, because the round class has no member left in the
// alphabet: a user who typed one of them misread a glyph that could have been
// several things, and guessing which would turn one typed code into a different
// real one. They are refused, like any other character outside the alphabet.
//
// It returns ErrAuthFailed for any malformed input, bare and with no cause. A
// caller must not learn whether the code it typed was the wrong length, held a
// character outside the alphabet, or was simply not a code anyone issued: those
// three answers together are a filter that makes guessing dramatically cheaper.
func normalizeUserCode(code string) (string, error) {
	var b strings.Builder
	b.Grow(userCodeLen)
	for _, r := range strings.ToUpper(code) {
		switch r {
		case '-', ' ':
			continue
		case '1', 'I':
			r = 'L'
		}
		if !strings.ContainsRune(userCodeAlphabet, r) {
			return "", ErrAuthFailed
		}
		if b.Len() == userCodeLen {
			// Refuse rather than truncate. A prefix check would accept every
			// code with the right first eight symbols, so a guess would only
			// have to be right about a prefix.
			return "", ErrAuthFailed
		}
		b.WriteRune(r)
	}
	if b.Len() != userCodeLen {
		return "", ErrAuthFailed
	}
	return b.String(), nil
}

// formatDeviceCode renders the one and only string a pairing client ever
// receives: "svd_<id>.<secret>".
//
// The identifier travels with the secret so the server can find the row to
// compare against without indexing the secret. The result is a secrets.Redacted
// from the moment it exists, so it cannot be logged, printed or marshaled by
// accident; the caller hands it to the client once and drops it.
func formatDeviceCode(id domain.PairingID, secret []byte) secrets.Redacted {
	return secrets.NewRedacted(deviceCodePrefix + string(id) + tokenSeparator + tokenEncoding.EncodeToString(secret))
}

// parseDeviceCode splits a presented device code into its identifier and secret.
//
// Every malformed shape returns bare ErrAuthFailed, for the same reason
// normalizeUserCode does. The parse is strict -- exact prefix, exactly one
// separator, exact decoded lengths -- because anything looser hands the store a
// value the issuer could never have produced.
func parseDeviceCode(presented secrets.Redacted) (domain.PairingID, []byte, error) {
	body, ok := strings.CutPrefix(presented.Reveal(), deviceCodePrefix)
	if !ok {
		return "", nil, ErrAuthFailed
	}
	idPart, secretPart, ok := strings.Cut(body, tokenSeparator)
	if !ok || strings.Contains(secretPart, tokenSeparator) {
		return "", nil, ErrAuthFailed
	}
	if len(idPart) != credentialIDChars {
		return "", nil, ErrAuthFailed
	}
	if _, err := tokenEncoding.DecodeString(idPart); err != nil {
		return "", nil, ErrAuthFailed
	}
	secret, err := tokenEncoding.DecodeString(secretPart)
	if err != nil || len(secret) != pairingSecretBytes {
		return "", nil, ErrAuthFailed
	}
	return domain.PairingID(idPart), secret, nil
}
